DevNet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .api_urls import urlpatterns as api_urlpatterns

urlpatterns = [
    url(r'^$', include('welcome.urls')),
    url(r'^profile/', include('profiles.urls')),
    url(r'^notification/', include('user_notifications.urls')),
    url(r'^project/', include('projects.urls')),
    url(r'^ratings/', include('ratings.urls')),

    url(r"^account/", include("account.urls")),
    url(r'^notifications/', include('notifications.urls')),
    url(r'', include('user_sessions.urls', 'user_sessions')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += api_urlpatterns

main/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^', views.index, name='homepage'),
]

projects/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^all/$', views.list_all, name='projects_list_all'),
    url(r'^category/(?P<category>.+)/$', views.list_category, name='projects_list_category'),
    url(r'^view/(?P<slug>.+)/$', views.view_project, name='projects_view_project'),
    url(r'^create/$', views.create, name='projects_create'),
]

ratings/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^add/$', views.add_rating, name='ratings_add_rating'),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify

from model_utils.models import TimeStampedModel

from ratings.models import Rating
from skills.models import Skill
from categories.models import Category

from .managers import ProjectManager


class Project(TimeStampedModel):
    author = models.ForeignKey(User)
    category = models.ForeignKey(Category)

    title = models.CharField(max_length=128)
    description = models.TextField()
    image = models.ImageField(upload_to='media/projects/', blank=True)
    slug = models.SlugField()
    
    required_skill_set = models.ManyToManyField(Skill)

    objects = models.Manager()
    manager = ProjectManager()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = slugify(self.title)

        super(Project, self).save(*args, **kwargs)

    @property
    def default_image(self):
        return "http://image-link-archive.meteor.com/images/placeholder-640x480.png"


class ProjectParticipant(TimeStampedModel):
    project = models.ForeignKey(Project)
    user = models.ForeignKey(User)

projects/forms.py
from django import forms

from .models import Project


class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ('title', 'description', 'image', 'category', 'required_skill_set')

projects/api/views.py
from rest_framework import generics

from ..models import Project
from .serializers import ProjectSerializer


class ProjectList(generics.ListCreateAPIView):
    serializer_class = ProjectSerializer

    def get_queryset(self):
        try:
            return Project.objects.filter(category__slug=self.kwargs['category'])
        except KeyError:
            return Project.objects.all()


class ProjectDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer


class ProjectDetailBySlug(generics.RetrieveUpdateDestroyAPIView):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer
    lookup_field = 'slug'

projects/views.py
from django.shortcuts import render
from categories.models import Category

from .forms import ProjectForm


def list_all(request):
    context = {}

    return render(request, 'projects/list_all.html', context)


def list_category(request, category):
    context = {
        'category': category,
    }

    return render(request, 'projects/list_category.html', context)


def view_project(request, slug):
    context = {
        'slug': slug,
    }

    return render(request, 'projects/view_project.html', context)


def create(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)

        if form.is_valid():
            project = form.save(commit=False)
            project.author = request.user
            project.save()

            form.save_m2m()
    else:
        form = ProjectForm()

    context = {
        'form': form,
    }

    return render(request, 'projects/create.html', context)

templates/projects/_project_box.html
{% load ratingtags %}

<div class="ui card">
    <div class="content">
        <div class="right floated meta">
            {{ project.created|date:"d. F, Y" }}
        </div>
        <img class="ui avatar image" src="{{ project.author.get_avatar }}" />
        {{ project.author.get_full_name|default:project.author.username }}
    </div>

    <div class="image">
        <img src="{{ project.image|default:project.default_image }}" />
    </div>

    <div class="content">
        <a class="header">{{ project }}</a>
    </div>

    <div class="extra content">
        <span class="right floated">
            {% get_rating project as rating %}
            <div class="ui rating" data-rating="{{ rating.total_score }}" data-max-rating="5"></div>
        </span>

        <i class="users icon"></i>
        {{ project.projectparticipant_set.all|length }} contributors
    </div>
</div>

templates/projects/create.html
{% extends 'layout.html' %}

{% load i18n %}
{% load staticfiles %}
{% load semanticui %}

{% block ng_controller %}ProjectEditController{% endblock %}

{% block content %}
    {% verbatim %}
    <form class="ui form {{ formClass }}" enctype="multipart/form-data">
    {% endverbatim %}
        {% csrf_token %}

        <h4 class="ui dividing header">Create new Project</h4>

        {% verbatim %}
        <div class="ui error message ng-hide" ng-show="errors">
            <div class="header">There are errors in form:</div>

            <p ng-repeat="(name, errs) in errors" class="alert alert-danger"><strong>{{ name|normalize }}</strong>: {{ errs.join(', ') }}</p>
        </div>
        {% endverbatim %}

        {% include 'snippets/form.html' with form=form %}

        <button class="ui green basic button" ng-click="save()">{% trans "Create" %}</button>
    </form>
    
    <div class="ui divider hidden"></div>
{% endblock %}

{% block body_js %}
    {{ block.super }}

    <script src="{% static 'js/models/Project.js' %}"></script>
    <script src="{% static 'js/controllers/ProjectController.js' %}"></script>
{% endblock %}

templates/projects/list_all.html
{% extends 'layout.html' %}

{% load staticfiles %}

{% block ng_controller %}ProjectsController{% endblock %}

{% block content %}
    <h2 class="ui dividing header page-header">All Projects</h2>

    {% verbatim %}
        <div class="ui cards">
            <div data-slug="{{ project.slug }}" class="ui card" ng-repeat="project in projects">
                <div class="content">
                    <div class="right floated meta">{{ project.created|date:"d. MMM, H:mm" }}</div>
                    <img src="{{ project.author_avatar }}" class="ui avatar image">
                    <span>{{ project.author }}</span>
                </div>

                <div class="image">
                    <img src="{{ project.preview_image }}">
                </div>

                <div class="content">
                    <a href="{{ project.url }}" class="header">{{ project.title }}</a>
                </div>

                <div class="extra content">
                    <span class="right floated">
                        <div class="ui rating" data-rating="{{ project.rating }}" data-max-rating="5"></div>
                    </span>

                    <i class="users icon"></i>
                    <span>{{ project.contributor_count }} contributors</span>
                </div>
            </div>
        </div>
    {% endverbatim %}
{% endblock %}

{% block body_js %}
    {{ block.super }}

    <script src="{% static 'js/models/Project.js' %}"></script>
    <script src="{% static 'js/controllers/ProjectsController.js' %}"></script>
{% endblock %}

templates/projects/list_category.html
{% extends 'layout.html' %}

{% load staticfiles %}

{% block ng_controller %}CategoryProjectsController{% endblock %}

{% block ng_init %}init('{{ category }}'){% endblock %}

{% block content %}
    {% verbatim %}
        <h2 class="ui dividing header page-header">{{ category.title }}</h2>

        <div class="ui cards">
            <div data-slug="{{ project.slug }}" class="ui card" ng-repeat="project in projects">
                <div class="content">
                    <div class="right floated meta">{{ project.created|date:"d. MMM, H:mm" }}</div>
                    <img src="{{ project.author_avatar }}" class="ui avatar image">
                    <span>{{ project.author }}</span>
                </div>

                <div class="image">
                    <img src="{{ project.preview_image }}">
                </div>

                <div class="content">
                    <a href="{{ project.url }}" class="header">{{ project.title }}</a>
                </div>

                <div class="extra content">
                    <span class="right floated">
                        <div class="ui rating" data-rating="{{ project.rating }}" data-max-rating="5"></div>
                    </span>

                    <i class="users icon"></i>
                    <span>{{ project.contributor_count }} contributors</span>
                </div>
            </div>
        </div>
    {% endverbatim %}
{% endblock %}

{% block body_js %}
    {{ block.super }}

    <script src="{% static 'js/models/Project.js' %}"></script>
    <script src="{% static 'js/controllers/ProjectsController.js' %}"></script>
{% endblock %}

templates/projects/view_project.html
{% extends 'layout.html' %}

{% load staticfiles %}
{% load ratingtags %}

{% get_rating project as rating %}

{% block ng_controller %}ProjectController{% endblock %}

{% block ng_init %}init('{{ slug }}'){% endblock %}

{% block content %}
    {% verbatim %}
    <div class="ui grid">
        <div class="four wide column">
            <div class="ui card">
                <div class="image">
                    <img src="{{ project.preview_image }}" alt="{{ project.title }}"/>
                </div>

                <div class="content text-center">
                    <a class="ui green button">
                        <i class="check square icon"></i>
                        Participate
                    </a>
                </div>

                <div class="extra content">
                    <div class="ui three column grid text-center">
                        <div class="row">
                            <div class="column">
                                <i class="users icon"></i>
                                {{ project.contributor_count }}
                            </div>

                            <div class="column">
                                <i class="star icon"></i>
                                {{ project.rating }}
                            </div>

                            <div class="column">
                                <i class="comments icon"></i>
                                10
                            </div>
                        </div>
                    </div>
                </div>

                <div class="content">
                    <div class="ui vertical fluid buttons">
                        <a class="ui labeled icon purple basic button">
                            <i class="user icon"></i>
                            Author Profile
                        </a>

                        <a class="ui labeled icon blue basic button">
                            <i class="mail icon"></i>
                            Send Message
                        </a>

                        <a class="ui labeled icon red basic button">
                            <i class="warning sign icon"></i>
                            Report Project
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="twelve wide column">
            <h1 class="ui header page-header">{{ project.title }}</h1>

            <div class="ui grid">
                <div class="row">
                    <div class="column teal">
                        <h3>
                            <i class="circle info icon"></i>
                            About
                        </h3>
                    </div>
                </div>

                <div class="row">
                    <div class="column">
                        <p>
                            {{ project.description }}
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="column">
                        <a class="ui brown label popup-item" data-content="Category" href="{{ project.category_url }}">
                            <i class="tags icon"></i>
                            {{ project.category }}
                        </a>

                        <a class="ui olive label popup-item" data-content="Required skill" ng-repeat="skill in project.required_skill_set">
                            <i class="student icon"></i>
                            {{ skill }}
                        </a>
                    </div>
                </div>
            </div>

            <div class="ui hidden divider"></div>

            <div class="ui grid">
                <div class="row">
                    <div class="column teal">
                        <h3>
                            <i class="comments icon"></i>
                            Comments
                        </h3>
                    </div>
                </div>

                <div class="row">
                    <div class="column">
                        <div class="ui comments" style="max-width: none">
                            <div class="comment">
                                <a class="avatar">
                                    <img src="http://semantic-ui.com/images/avatar/small/matt.jpg">
                                </a>

                                <div class="content">
                                    <a class="author">Matt</a>

                                    <div class="metadata">
                                        <span class="date">Today at 5:42PM</span>
                                    </div>
                                    <div class="text">
                                        How artistic!
                                    </div>
                                    <div class="actions">
                                        <a class="reply">Reply</a>
                                    </div>
                                </div>
                            </div>
                            <div class="comment">
                                <a class="avatar">
                                    <img src="http://semantic-ui.com/images/avatar/small/elliot.jpg">
                                </a>

                                <div class="content">
                                    <a class="author">Elliot Fu</a>

                                    <div class="metadata">
                                        <span class="date">Yesterday at 12:30AM</span>
                                    </div>
                                    <div class="text">
                                        <p>This has been very useful for my research. Thanks as well!</p>
                                    </div>
                                    <div class="actions">
                                        <a class="reply">Reply</a>
                                    </div>
                                </div>
                                <div class="comments">
                                    <div class="comment">
                                        <a class="avatar">
                                            <img src="http://semantic-ui.com/images/avatar/small/jenny.jpg">
                                        </a>

                                        <div class="content">
                                            <a class="author">Jenny Hess</a>

                                            <div class="metadata">
                                                <span class="date">Just now</span>
                                            </div>
                                            <div class="text">
                                                Elliot you are always so right :)
                                            </div>
                                            <div class="actions">
                                                <a class="reply">Reply</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="comment">
                                <a class="avatar">
                                    <img src="http://semantic-ui.com/images/avatar/small/joe.jpg">
                                </a>

                                <div class="content">
                                    <a class="author">Joe Henderson</a>

                                    <div class="metadata">
                                        <span class="date">5 days ago</span>
                                    </div>
                                    <div class="text">
                                        Dude, this is awesome. Thanks so much
                                    </div>
                                    <div class="actions">
                                        <a class="reply">Reply</a>
                                    </div>
                                </div>
                            </div>

                            <form class="ui reply form">
                                <div class="field">
                                    <textarea class="fluid"></textarea>
                                </div>
                                <div class="ui blue labeled submit icon button">
                                    <i class="icon edit"></i> Add Reply
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="ui hidden divider"></div>
        </div>
    </div>
    {% endverbatim %}
{% endblock %}

{% block body_js %}
    {{ block.super }}

    <script src="{% static 'js/models/Project.js' %}"></script>
    <script src="{% static 'js/controllers/ProjectController.js' %}"></script>
{% endblock %}